"""sendWordModel

Revision ID: 207aa0cff0e9
Revises: 
Create Date: 2019-03-31 00:25:28.790617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207aa0cff0e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_word')
    # ### end Alembic commands ###
